# Generated by Django 3.2.6 on 2021-10-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_auto_20211023_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(verbose_name='Price:'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='weight',
            field=models.FloatField(verbose_name='Weight:'),
        ),
    ]
